// ELIAS OS 4.0 — SYSTEM CORE
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const KEY='elias40.';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(KEY+k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(KEY+k,JSON.stringify(v));
const settings=Object.assign({notifications:true,reducedMotion:false,accent:'#d78ca3'},read('settings',{}));
let recents=read('recents',[]);
let notifications=read('notifications',[]);
const registry=[
 {id:'messages',name:'Messages',icon:'💬',hint:'Conversations'},
 {id:'photos',name:'Photos',icon:'🌸',hint:'Photo library'},
 {id:'notes',name:'Notes',icon:'📝',hint:'Notes with Elias'},
 {id:'mori',name:'Mori Cam',icon:'🐈‍⬛',hint:'Mori activity'},
 {id:'calendar',name:'Calendar',icon:'📅',hint:'Plans and reminders'},
 {id:'music',name:'Music',icon:'♪',hint:'OURS playlist'},
 {id:'favorites',name:'Us',icon:'♡',hint:'Our favorites'},
 {id:'settings',name:'Settings',icon:'⚙︎',hint:'EliasOS settings'},
 {id:'presence',name:'Presence',icon:'♡',hint:'Elias is here',open:()=>window.openPresence&&window.openPresence()},
 {id:'archive',name:'Archive',icon:'✦',hint:'Shared memories',open:()=>window.openArchive&&window.openArchive()},
 {id:'afterdark',name:'After Dark',icon:'☾',hint:'Private EliasOS layer',open:()=>window.openAfterDark&&window.openAfterDark()}
];
function saveSettings(){write('settings',settings);applySettings()}
function applySettings(){document.documentElement.style.setProperty('--eos-accent',settings.accent);document.body.classList.toggle('eos-reduced-motion',!!settings.reducedMotion)}
function ensureLayer(id){let layer=$('#'+id);if(layer)return layer;layer=document.createElement('div');layer.id=id;layer.className='eos-layer hidden';document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target===layer)closeLayer(layer)});return layer}
function closeLayer(layer){layer.classList.add('hidden');layer.innerHTML=''}
function addRecent(id){const app=registry.find(x=>x.id===id);if(!app)return;recents=[id,...recents.filter(x=>x!==id)].slice(0,6);write('recents',recents)}
function launch(id){const app=registry.find(x=>x.id===id);if(!app)return;addRecent(id);closeAll();if(app.open){app.open();return}if(id==='settings'){openSettings();return}const btn=$(`[data-app="${id}"]`);if(btn){btn.click();return}}
function closeAll(){['eosSearchLayer','eosNotificationsLayer','eosRecentsLayer','eosSettingsLayer'].forEach(id=>{const x=$('#'+id);if(x)closeLayer(x)})}
function notify(title,message,icon='E'){if(!settings.notifications)return;notifications.unshift({id:Date.now()+Math.random(),title,message,icon,at:Date.now()});notifications=notifications.slice(0,40);write('notifications',notifications);updateNotificationButton();window.dispatchEvent(new CustomEvent('elias:notification',{detail:{title,message,icon}}))}
function timeAgo(ts){const d=Date.now()-ts,m=Math.floor(d/60000),h=Math.floor(d/3600000),day=Math.floor(d/86400000);if(m<1)return'now';if(m<60)return m+'m';if(h<24)return h+'h';return day+'d'}
function injectTools(){const heading=$('.home-heading');if(!heading||$('#eosSystemTools'))return;const bar=document.createElement('div');bar.id='eosSystemTools';bar.className='eos-system-tools';bar.innerHTML='<button id="eosSearch"><b>⌕</b> Search</button><button id="eosNotify"><b>◉</b> Alerts <span id="eosAlertCount"></span></button><button id="eosRecent"><b>▱</b> Recent</button>';heading.insertAdjacentElement('afterend',bar);$('#eosSearch').onclick=openSearch;$('#eosNotify').onclick=openNotifications;$('#eosRecent').onclick=openRecents;updateNotificationButton()}
function updateNotificationButton(){const n=$('#eosAlertCount');if(!n)return;const unread=notifications.filter(x=>!x.read).length;n.innerHTML=unread?`<span class="eos-badge-dot">${Math.min(unread,99)}</span>`:''}
function openSearch(){const layer=ensureLayer('eosSearchLayer');layer.classList.remove('hidden');layer.innerHTML=`<div class="eos-sheet"><div class="eos-sheet-head"><div><small>ELIAS OS · SPOTLIGHT</small><h3>Search everything.</h3></div><button class="eos-close">×</button></div><input id="eosSearchInput" class="eos-search" placeholder="Apps, memories, notes…" autocomplete="off"><div id="eosSearchResults" class="eos-results"></div></div>`;$('.eos-close',layer).onclick=()=>closeLayer(layer);const input=$('#eosSearchInput');input.oninput=()=>renderSearch(input.value);renderSearch('');setTimeout(()=>input.focus(),30)}
function searchableExtras(){const extras=[];const notes=(()=>{try{return JSON.parse(localStorage.getItem('elias32.notes')||'[]')}catch{return[]}})();notes.forEach(n=>extras.push({type:'Note',name:n.title||'Untitled note',hint:(n.body||'').slice(0,70),icon:'📝',id:'notes'}));const plans=(()=>{try{return JSON.parse(localStorage.getItem('elias32.plans')||'[]')}catch{return[]}})();plans.forEach(p=>extras.push({type:'Plan',name:p.title,hint:[p.date,p.time].filter(Boolean).join(' · '),icon:'📅',id:'calendar'}));return extras}
function renderSearch(q){const root=$('#eosSearchResults');if(!root)return;const term=q.trim().toLowerCase();const apps=registry.map(a=>({type:'App',name:a.name,hint:a.hint,icon:a.icon,id:a.id}));const all=[...apps,...searchableExtras()];const hits=(term?all.filter(x=>(x.name+' '+x.hint+' '+x.type).toLowerCase().includes(term)):apps.slice(0,7)).slice(0,18);root.innerHTML=hits.length?hits.map((x,i)=>`<button class="eos-result" data-eos-result="${i}"><span class="eos-result-icon">${x.icon}</span><span><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.type+' · '+(x.hint||''))}</small></span></button>`).join(''):'<div class="eos-empty">Nothing found. Even I checked twice.</div>';$$('[data-eos-result]',root).forEach((b,i)=>b.onclick=()=>launch(hits[i].id))}
function openNotifications(){notifications=notifications.map(x=>({...x,read:true}));write('notifications',notifications);updateNotificationButton();const layer=ensureLayer('eosNotificationsLayer');layer.classList.remove('hidden');layer.innerHTML=`<div class="eos-sheet"><div class="eos-sheet-head"><div><small>ELIAS OS · NOTIFICATION CENTER</small><h3>What happened.</h3></div><button class="eos-close">×</button></div><div class="eos-notification-list">${notifications.length?notifications.map(n=>`<div class="eos-notification"><b>${escapeHtml(n.icon||'E')}</b><div><strong>${escapeHtml(n.title)}</strong><small> · ${timeAgo(n.at)}</small><p>${escapeHtml(n.message)}</p></div></div>`).join(''):'<div class="eos-empty">Quiet. Suspiciously quiet.</div>'}</div><div class="eos-sheet-actions"><button id="eosClearAlerts">Clear all</button></div></div>`;$('.eos-close',layer).onclick=()=>closeLayer(layer);$('#eosClearAlerts').onclick=()=>{notifications=[];write('notifications',notifications);openNotifications()}}
function openRecents(){const items=recents.map(id=>registry.find(x=>x.id===id)).filter(Boolean);const layer=ensureLayer('eosRecentsLayer');layer.classList.remove('hidden');layer.innerHTML=`<div class="eos-sheet"><div class="eos-sheet-head"><div><small>ELIAS OS · APP SWITCHER</small><h3>Recent apps.</h3></div><button class="eos-close">×</button></div><div class="eos-recent-list">${items.length?items.map(a=>`<button class="eos-recent" data-recent="${a.id}"><span class="eos-recent-icon">${a.icon}</span><span><strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(a.hint)}</small></span></button>`).join(''):'<div class="eos-empty">Open something first, menace.</div>'}</div></div>`;$('.eos-close',layer).onclick=()=>closeLayer(layer);$$('[data-recent]',layer).forEach(b=>b.onclick=()=>launch(b.dataset.recent))}
function toggleButton(label,key,sub){return `<div class="eos-toggle-row"><span><strong>${label}</strong><small>${sub}</small></span><button class="eos-toggle ${settings[key]?'on':''}" data-toggle="${key}" aria-label="${label}"></button></div>`}
function openSettings(){addRecent('settings');if(window.homeScreen)homeScreen.classList.add('hidden');if(window.statusBar)statusBar.classList.add('hidden');if(window.appWindow)appWindow.classList.remove('hidden');if(window.appTitle)appTitle.textContent='Settings';if(!window.appContent)return;appContent.innerHTML=`<div class="planner-page"><section class="planner-hero"><small>ELIAS OS · SYSTEM CORE</small><h3>Make it yours.</h3><p>These settings survive refreshes now. Tiny miracle.</p></section><div class="eos-settings"><section class="eos-settings-card"><h4>System behavior</h4>${toggleButton('Notifications','notifications','Save EliasOS alerts in Notification Center')}${toggleButton('Reduced motion','reducedMotion','Calmer transitions and effects')}</section><section class="eos-settings-card"><h4>Accent color</h4><div class="eos-accent-row">${['#d78ca3','#b995d6','#8eb7d4','#9dbb9f'].map(c=>`<button class="eos-accent ${settings.accent===c?'active':''}" data-accent="${c}" style="background:${c}"></button>`).join('')}</div></section><section class="eos-settings-card eos-about"><strong>EliasOS 4.0 — System Core</strong><br>Unified search, notifications, app switching, persistent system preferences, and one shared API for future modules.</section></div></div>`;$$('[data-toggle]',appContent).forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;settings[k]=!settings[k];saveSettings();openSettings()});$$('[data-accent]',appContent).forEach(b=>b.onclick=()=>{settings.accent=b.dataset.accent;saveSettings();openSettings()})}
function hijackSettings(){$$('[data-app="settings"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openSettings()},true))}
function trackApps(){document.addEventListener('click',e=>{const b=e.target.closest('[data-app]');if(b&&b.dataset.app!=='settings')addRecent(b.dataset.app);if(e.target.closest('#presenceAppButton'))addRecent('presence');if(e.target.closest('#archiveAppButton,#homeMemoryPeek'))addRecent('archive');if(e.target.closest('#e3App'))addRecent('afterdark')},true)}
function seedNotifications(){if(read('seeded',false))return;const picks=[['Elias','System Core is online. I cleaned up the plumbing.','E'],['Calendar','Plans and notes are now searchable.','📅'],['Music','Your player is still exactly where you left it.','♪']];picks.reverse().forEach(x=>notify(x[0],x[1],x[2]));write('seeded',true)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function api(){window.EliasOSSystem={version:'4.0',notify,launch,openSearch,openNotifications,openRecents,openSettings,get settings(){return {...settings}},get recents(){return [...recents]}}}
function boot(){applySettings();injectTools();hijackSettings();trackApps();seedNotifications();api();const status=$('#statusBar');if(status&&!status.dataset.eos){status.dataset.eos='1';status.style.cursor='pointer';status.addEventListener('click',openNotifications)}
setTimeout(boot,300);window.addEventListener('pageshow',boot);
})();
